name: Create release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: release tag value
        required: true

jobs:
  create_release_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Create zip
        run: |
          zip -r ${{ inputs.release_tag }}.zip .* -x .git/**
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.release_tag }}.zip

  publish_release_zip:
    needs: create_release_zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/checkout@v4
      - name: create release
        run: |
          gh release create ${{ inputs.release_tag }} --generate-notes
          gh release upload ${{ inputs.release_tag }} artifact/${{ inputs.release_tag }}.zip
        env:
          GH_TOKEN: ${{ github.token }}