name: Create PR for 'main'
on:
  workflow_dispatch:

jobs:
  linting:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Reformat Code
        run: |
          ls -alt 
          pip install black
          black .
          echo ".github" > .gitignore
          git add .
          git config --global user.name "Github Actions Bot"
          git config --global user.email ""
          git commit -m 'Changes by Github Actions'
          git push origin develop
          gh pr create --base main --title "${{ github.sha }}" --body "PR by Github Actions Bot. Please verify before merge!"
