name: Create release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: release tag value
        required: true

jobs:
  create_release_zip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: main
      - name: Create zip
        run: |
          zip -r ${{ inputs.release_tag }}.zip .* -x .git/**
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          path: ${{ inputs.release_tag }}.zip

  publish_release_zip:
    needs: create_release_zip
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: create release
        run: |
          gh release create ${{ inputs.release_tag }} --generate-notes
          gh release upload ${{ inputs.release_tag }} artifact/${{ inputs.release_tag }}.zip
        env:
          GH_TOKEN: ${{ github.token }}