name: pypi-publish-workflow.yml
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build
        run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: dist
          path: ${{ github.workspace }}/dist
  pypi-publish:
    needs: build
    name: Publish on PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/dist
      - run: |
          ls -alt
          ls -alt dist
      - name: Publish package to PyPI
        if: false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ vars.PYPI_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://pypi.org/project/FireEye-AWS/0.6.0.dev0/